### ISSUE TITLE
Suggestion: don't suppress parser errors

### ISSUE THREAD

**Issue by rpgoldman** [amestsantim/pycspro#1]
In [DictionaryParser.py](https://github.com/tech-acs/pycspro/blob/3bf75237f7827b45ef6ce3208763f240c0733485/pycspro/DictionaryParser.py#L231-L240) parsing errors are trapped, and instead of being signaled, the error message is returned from the `parse()` method.

I'd like to suggest that this trapping be removed. If the trapping is there, then any calling code has to check the return value, which will give back nonsense. If the error is allowed to propagate, the calling code won't be in danger of accidentally trying to use an error message for further processing (which gives oddball errors later in the code) and will have the option of getting at a backtrace where the error occurred instead of a backtrace in follow-on processing.

Thanks for the library! It's been a huge help in dealing with some third party data in CSPro format!

**Comment by amestsantim** [comment]
Thank you!
I am glad you found it helpful!
Pull requests are also welcome :-)

**Comment by rpgoldman** [comment]
OK! See #2

**Comment by rpgoldman** [comment]
Fixed with #2
